name: Deploy Lambda Function

on: workflow_dispatch


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2
